bots:
  - protocol: 'ws'
    endpoint: 'ws://localhost:6700'
    selfId: '1111111111'
    token: 'token'
routes:
  - name: default
    botId: '3221204940'
    token: 'oONw7YpqUdYuc'
    balancePolicy: hash
